# Generated by Django 4.0 on 2021-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='recipie',
            name='category',
            field=models.ManyToManyField(blank=True, to='recipies.Category'),
        ),
    ]
